- name: Remove unnecessary stuff
  file:
    path: "{{ ansistrano_release_path.stdout }}/{{ item }}"
    state: absent
  loop:
  - ansible
  - deploy.yml
  - .docker-config
  - docker-compose-linux.yml
  - docker-compose-osx.yml
  - docker-compose-windows.yml
  - .git
  - .gitlab-ci.yml
  - .gitattributes
  - .gitignore
